In [4]:
%reset

# 1. Imports

In [11]:
import mne
import time
import os
import numpy as np
import custom_modules.xdf_to_fif_converter as xtfc
import custom_modules.preprocessing_ptu as prep
import custom_modules.file_handling as  fh
import custom_modules.processing_ptu as proc
import custom_modules.classification_ptu as clas

import importlib
importlib.reload(xtfc)
importlib.reload(prep)
importlib.reload(fh)
importlib.reload(proc)
importlib.reload(clas)

<module 'custom_modules.classification_ptu' from 'C:\\Users\\peter\\Documents\\Code\\master-thesis\\03_analysis\\custom_modules\\classification_ptu.py'>

# 2. Constants

In [12]:
data_path = 'D:/Diplomarbeit_data/eeg/'
subjects = ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07' , 'A08', 'A09', 'A10']
trial_type_markers = ['LTR-s', 'LTR-l','RTL-s', 'RTL-l', 'TTB-s', 'TTB-l', 'BTT-s', 'BTT-l']

# Paths to interface files:
# path_cue_aligned_resampled = '2023_03_22_epoched_cue_aligned'
# path_movement_aligned_resampled = '2023_03_22_epoched_movement_aligned'
# path_cue_aligned_not_resampled = '2023_03_22_epoched_cue_aligned_not_resampled'
# path_movement_aligned_not_resampled = '2023_03_22_epoched_movement_aligned_not_resampled'

path_cue_aligned_resampled = '2023_05_24_epoched_cue_aligned'
path_movement_aligned_resampled = '2023_05_24_epoched_movement_aligned'
path_cue_aligned_not_resampled = '2023_05_24_epoched_cue_aligned_not_resampled'
path_movement_aligned_not_resampled = '2023_05_24_epoched_movement_aligned_not_resampled'

__spec__ = None # For multiprocessing
mne.set_log_level('WARNING') #'INFO' 'WARNING'

# 3. Temporal analysis

## 3.1. Cue-aligned

In [7]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_cue_aligned_not_resampled, dst_fldr='results')

# Calculate the grand averages per subject:
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=0)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=1)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=2)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=3)

In [14]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_cue_aligned_not_resampled, dst_fldr='results')

# Get timings of the cues:
# TODO: Add split if necessary to separate between conditions.
proc.get_timings(src_path, dst_path, subjects, split_id=0)
proc.get_timings(src_path, dst_path, subjects, split_id=1)
# proc.get_timings(src_path, dst_path, subjects, split_id=2)
# proc.get_timings(src_path, dst_path, subjects, split_id=3)

In [9]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

# Calculate the condition specific grand averages over all subjects:
proc.grand_avg(src_path, dst_path, split_id=0, alignment='cue-aligned')
proc.grand_avg(src_path, dst_path, split_id=1, alignment='cue-aligned')
proc.grand_avg(src_path, dst_path, split_id=2, alignment='cue-aligned')
proc.grand_avg(src_path, dst_path, split_id=3, alignment='cue-aligned')

In [ ]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

# Calculate the confidence interval:
proc.confidence_interval(src_path, dst_path, split_id=0, alignment='cue-aligned')

In [ ]:
proc.confidence_interval(src_path, dst_path, split_id=1, alignment='cue-aligned')

In [ ]:
proc.confidence_interval(src_path, dst_path, split_id=2, alignment='cue-aligned')

In [ ]:
proc.confidence_interval(src_path, dst_path, split_id=3, alignment='cue-aligned')

## 3.2. Movement-aligned

In [ ]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_movement_aligned_not_resampled, dst_fldr='results')

# Calculate the grand averages per subject:
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=0)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=1)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=2)
proc.grand_avg_per_subject(src_path, dst_path, subjects, split_id=3)

In [15]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_movement_aligned_not_resampled, dst_fldr='results')

# Get timings of the cues:
# TODO: Add split if necessary to separate between conditions.
proc.get_timings(src_path, dst_path, subjects, split_id=0)
proc.get_timings(src_path, dst_path, subjects, split_id=1)
# proc.get_timings(src_path, dst_path, subjects, split_id=2)
# proc.get_timings(src_path, dst_path, subjects, split_id=3)

In [16]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

# Calculate the condition specific grand averages over all subjects:
proc.grand_avg(src_path, dst_path, split_id=0, alignment='movement-aligned')
proc.grand_avg(src_path, dst_path, split_id=1, alignment='movement-aligned')
proc.grand_avg(src_path, dst_path, split_id=2, alignment='movement-aligned')
proc.grand_avg(src_path, dst_path, split_id=3, alignment='movement-aligned')

In [16]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

# Calculate the confidence interval:
proc.confidence_interval(src_path, dst_path, split_id=0, alignment='movement-aligned')

One condition took me: 137.49


In [17]:
proc.confidence_interval(src_path, dst_path, split_id=1, alignment='movement-aligned')

One condition took me: 144.23
One condition took me: 127.91


In [18]:
proc.confidence_interval(src_path, dst_path, split_id=2, alignment='movement-aligned')

KeyboardInterrupt: 

In [ ]:
proc.confidence_interval(src_path, dst_path, split_id=3, alignment='movement-aligned')

# 4. Classification analysis

## 4.1. Cue-aligned

In [21]:
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_cue_aligned_resampled, dst_fldr='results')

# Iterate over each subject and extract the streams
start = time.time()
for i, subject in enumerate(subjects):
    print(f'Classifying cue-aligned for subject {subject}')

    ### Distance
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='distance', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='distance', n_timepoints=6, loo=True)

    ### Direction
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction', n_timepoints=6, loo=True)

    ### Direction short
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_short', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_short', n_timepoints=6, loo=True)

    ### Direction long
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_long', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_long', n_timepoints=6, loo=True)

    ### Position
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='position', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='position', n_timepoints=6, loo=True)


print(f'Finished classifying, took me {round(time.time() - start)} seconds...')

Classifying cue-aligned for subject A01
Measuring timestamp 70/70, shape: (250, 61)

Measuring timestamp 65/65, shape: (250, 366)
Measuring timestamp 70/65, shape: (250, 366)
Measuring timestamp 70/70, shape: (232, 61)

Measuring timestamp 65/65, shape: (232, 366)
Measuring timestamp 70/65, shape: (232, 366)
Measuring timestamp 70/70, shape: (116, 61)

Measuring timestamp 65/65, shape: (116, 366)
Measuring timestamp 70/65, shape: (116, 366)
Measuring timestamp 70/70, shape: (112, 61)

Measuring timestamp 65/65, shape: (112, 366)
Measuring timestamp 70/65, shape: (112, 366)
Measuring timestamp 70/70, shape: (140, 61)

Measuring timestamp 65/65, shape: (140, 366)
Measuring timestamp 70/65, shape: (140, 366)
Classifying cue-aligned for subject A02
Measuring timestamp 70/70, shape: (298, 61)

Measuring timestamp 65/65, shape: (298, 366)
Measuring timestamp 70/65, shape: (298, 366)
Measuring timestamp 70/70, shape: (308, 61)

Measuring timestamp 65/65, shape: (308, 366)
Measuring timestamp 

## 4.2. Movement-aligned

In [22]:
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='2023_03_22_epoched_movement_aligned', dst_fldr='results')

# Iterate over each subject and extract the streams
start = time.time()
for i, subject in enumerate(subjects):
    print(f'Classifying movement-aligned for subject {subject}')

    ### Distance
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='distance', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='distance', n_timepoints=6, loo=True)

    ### Direction
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction', n_timepoints=6, loo=True)

    ### Direction short
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_short', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_short', n_timepoints=6, loo=True)

    ### Direction long
    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_long', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='direction_long', n_timepoints=6, loo=True)

    # Classify the epochs for 1 timepoint:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='position', n_timepoints=1, loo=True)
    # Classify the epochs for 6 timepoints:
    clas.classify(src=src_path, dst=dst_path, sbj=subject, condition='position', n_timepoints=6, loo=True)


print(f'Finished classifiying, took me {round(time.time() - start)} seconds...')

Classifying movement-aligned for subject A01
Measuring timestamp 60/60, shape: (250, 61)

Measuring timestamp 55/55, shape: (250, 366)
Measuring timestamp 60/55, shape: (250, 366)
Measuring timestamp 60/60, shape: (232, 61)

Measuring timestamp 55/55, shape: (232, 366)
Measuring timestamp 60/55, shape: (232, 366)
Measuring timestamp 60/60, shape: (116, 61)

Measuring timestamp 55/55, shape: (116, 366)
Measuring timestamp 60/55, shape: (116, 366)
Measuring timestamp 60/60, shape: (112, 61)

Measuring timestamp 55/55, shape: (112, 366)
Measuring timestamp 60/55, shape: (112, 366)
Measuring timestamp 60/60, shape: (140, 61)

Measuring timestamp 55/55, shape: (140, 366)
Measuring timestamp 60/55, shape: (140, 366)
Classifying movement-aligned for subject A02
Measuring timestamp 60/60, shape: (298, 61)

Measuring timestamp 55/55, shape: (298, 366)
Measuring timestamp 60/55, shape: (298, 366)
Measuring timestamp 60/60, shape: (308, 61)

Measuring timestamp 55/55, shape: (308, 366)
Measuring 

## 4.3. Mean and CI calculation for cue- & movement-aligned

In [23]:
importlib.reload(proc)
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

proc.classification_mean_and_ci(src_path, dst_path)

cue-aligned distance 1
cue-aligned direction 1
cue-aligned direction_short 1
cue-aligned direction_long 1
cue-aligned position 1
cue-aligned distance 6
cue-aligned direction 6
cue-aligned direction_short 6
cue-aligned direction_long 6
cue-aligned position 6
movement_aligned distance 1
movement_aligned direction 1
movement_aligned direction_short 1
movement_aligned direction_long 1
movement_aligned position 1
movement_aligned distance 6
movement_aligned direction 6
movement_aligned direction_short 6
movement_aligned direction_long 6
movement_aligned position 6
Calculation took me: 9.308835744857788seconds.


# 5. Encoding of conditions / calculate GLM

## 5.1. Cue-aligned

In [8]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_cue_aligned_not_resampled, dst_fldr='results')

# Calculate the confidence interval:
proc.glm(src_path, dst_path, sbj_list=subjects, split_id=0, alignment='cue-aligned', shrink=False)
proc.glm(src_path, dst_path, sbj_list=subjects, split_id=0, alignment='cue-aligned', shrink=True)

[[ 0.9985119  -0.99255952  0.          0.          0.        ]
 [-0.99255952  0.9985119   0.          0.          0.        ]
 [ 0.          0.          0.9985119  -0.99255952  0.        ]
 [ 0.          0.         -0.99255952  0.9985119   0.        ]
 [ 0.          0.          0.          0.          0.00595238]]
[[ 84.25112108  83.74887892   0.           0.           0.        ]
 [ 83.74887892  84.25112108   0.           0.           0.        ]
 [  0.           0.          84.25112108  83.74887892   0.        ]
 [ -0.          -0.          83.74887892  84.25112108  -0.        ]
 [  0.           0.           0.           0.         168.        ]]
Shrinkage param: 0.007440476190476189
[[ 0.99884259 -0.99421296  0.          0.          0.        ]
 [-0.99421296  0.99884259  0.          0.          0.        ]
 [ 0.          0.          0.99884259 -0.99421296  0.        ]
 [ 0.          0.         -0.99421296  0.99884259  0.        ]
 [ 0.          0.          0.          0.          0.

In [9]:
# Statistical analysis:
importlib.reload(proc)
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

proc.statistical_tests_glm(src_path, dst_path, split_id=0, alignment='cue-aligned', shrink=True)
proc.statistical_tests_glm(src_path, dst_path, split_id=0, alignment='cue-aligned', shrink=False)

61
Permutations tests took me: 940.3
61
Permutations tests took me: 926.68


In [10]:
# Statistical analysis:
importlib.reload(proc)
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

proc.two_sample_tests_glm(src_path, dst_path, split_id=0, alignment='cue-aligned', shrink=True)
proc.two_sample_tests_glm(src_path, dst_path, split_id=0, alignment='cue-aligned', shrink=False)

61
Permutations tests took me: 880.4
61
Permutations tests took me: 857.24


In [4]:
sign_list = [1,-1]
signs = np.random.choice(sign_list, size=(10, 30))
vals = [1,2,3,4,5,6,7,8,9,10]
vals = np.reshape(vals, (len(vals),1))
vals_rep = np.repeat(np.array(vals), 30, axis=1)

mult = vals_rep * signs

from scipy.stats import wilcoxon, ttest_ind, ttest_1samp
_stat, _pval = ttest_1samp(mult, popmean=0.0, axis=0)
orig_stat, orig_p = ttest_1samp(vals, popmean=0.0)
_stat.sort()

temp = _stat>orig_stat
temp[3] = True
temp[5] = True
ids_above = temp.sum()

In [108]:
p_s = np.load('D:/Diplomarbeit_data/eeg/results/regr_coeff_p_vals_cue-aligned.npy')

## 5.2. Movement-aligned

In [11]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_movement_aligned_not_resampled, dst_fldr='results')

# Calculate the confidence interval:
proc.glm(src_path, dst_path, sbj_list=subjects, split_id=0, alignment='movement-aligned', shrink=False)
proc.glm(src_path, dst_path, sbj_list=subjects, split_id=0, alignment='movement-aligned', shrink=True)

[[ 0.9985119  -0.99255952  0.          0.          0.        ]
 [-0.99255952  0.9985119   0.          0.          0.        ]
 [ 0.          0.          0.9985119  -0.99255952  0.        ]
 [ 0.          0.         -0.99255952  0.9985119   0.        ]
 [ 0.          0.          0.          0.          0.00595238]]
[[ 84.25112108  83.74887892   0.           0.           0.        ]
 [ 83.74887892  84.25112108   0.           0.           0.        ]
 [  0.           0.          84.25112108  83.74887892   0.        ]
 [ -0.          -0.          83.74887892  84.25112108  -0.        ]
 [  0.           0.           0.           0.         168.        ]]
Shrinkage param: 0.007440476190476189
[[ 0.99884259 -0.99421296  0.          0.          0.        ]
 [-0.99421296  0.99884259  0.          0.          0.        ]
 [ 0.          0.          0.99884259 -0.99421296  0.        ]
 [ 0.          0.         -0.99421296  0.99884259  0.        ]
 [ 0.          0.          0.          0.          0.

In [12]:
# Statistical analysis:
importlib.reload(proc)
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

proc.statistical_tests_glm(src_path, dst_path, split_id=0, alignment='movement-aligned', shrink=True)
proc.statistical_tests_glm(src_path, dst_path, split_id=0, alignment='movement-aligned', shrink=False)

61
Permutations tests took me: 762.11
61
Permutations tests took me: 757.6


In [13]:
# Statistical analysis:
importlib.reload(proc)#
# Get source and destination path + create destintation folder if it does not exist.
src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr='results', dst_fldr='results')

proc.two_sample_tests_glm(src_path, dst_path, split_id=0, alignment='movement-aligned', shrink=True)
proc.two_sample_tests_glm(src_path, dst_path, split_id=0, alignment='movement-aligned', shrink=False)

61
Permutations tests took me: 762.15
61
Permutations tests took me: 774.56


In [10]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
m = A.mean(axis=1)

In [35]:
S = np.load('C:/Users/peter/Documents/Code/master-thesis/test_shrinkage/param-matrix_A01_cue-aligned.npy')

emp_cov = 1/S.shape[0] * S.T.dot(S)

from sklearn.covariance import LedoitWolf
cov_ld = LedoitWolf().fit(S)
est_cov = cov_ld.covariance_

S_pinv = np.linalg.pinv(S)

S_pinv_cov = 1/S.shape[0] * np.linalg.inv(est_cov).dot(S.T)

## 5.3. Statistical analysis

In [51]:
import numpy as np
from sklearn.covariance import LedoitWolf
real_cov = np.array([[.4, .2], [.2, .8]])
np.random.seed(0)
X = np.random.multivariate_normal(mean=[0, 0], cov=real_cov, size=50)
cov = LedoitWolf().fit(X)
cov.covariance_
cov.location_

array([ 0.0595348 , -0.00756804])

In [59]:
X = np.array([[1,2],[3,4],[5,6],[7,8]])
Y = np.array([4,5,6])
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
x = X - X.mean(axis=0)
y = Y - Y.mean()

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 

In [64]:
S = np.ones((5,360))

In [69]:
S.dot(S.T)

array([[360., 360., 360., 360., 360.],
       [360., 360., 360., 360., 360.],
       [360., 360., 360., 360., 360.],
       [360., 360., 360., 360., 360.],
       [360., 360., 360., 360., 360.]])

In [166]:
importlib.reload(proc)

src_path, dst_path = fh.gen_paths(pth=data_path, src_fldr=path_cue_aligned_not_resampled, dst_fldr='results')

markers =  proc.glm(src_path, dst_path, 'A01')

TypeError: glm() missing 2 required positional arguments: 'split_id' and 'alignment'

In [76]:
longs = [m for m in markers if '-l' in m]
shorts = [m for m in markers if '-s' in m]
left_dir = [m for m in markers if 'RTL' in m]
right_dir = [m for m in markers if 'LTR' in m]
up_dir = [m for m in markers if 'BTT' in m]
down_dir = [m for m in markers if 'TTB' in m]
center_pos = [m for m in markers if '-s' in m]
left_pos = [m for m in markers if 'RTL-l' in m]
right_pos = [m for m in markers if 'LTR-l' in m]
top_pos = [m for m in markers if 'BTT-l' in m]
bot_pos = [m for m in markers if 'TTB-l' in m]

min_len = min(len(left_pos), len(right_pos), len(top_pos), len(left_pos), len(center_pos))